# Generated by Django 5.0.6 on 2025-04-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoriesPage', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
