# Generated by Django 5.0.6 on 2025-03-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review_title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('rating', models.CharField(choices=[('★☆☆☆☆', '1 Star'), ('★★☆☆☆', '2 Stars'), ('★★★☆☆', '3 Stars'), ('★★★★☆', '4 Stars'), ('★★★★★', '5 Stars')], default='★★★★★', max_length=5)),
                ('image', models.URLField()),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
